export const HttpStatus = {
	BAD_REQUEST: 'BAD_REQUEST',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	NOT_FOUND: 'NOT_FOUND',
	CONFLICT: 'CONFLICT',
	UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
	SUCCESS: 'SUCCESS',
	CREATED: 'CREATED',
	NO_CONTENT: 'NO_CONTENT',
	BAD_GATEWAY: 'BAD_GATEWAY',
	NOT_ACCEPTABLE: 'NOT_ACCEPTABLE',
	REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
} as const

export const ProductStatus = {
	PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
	PRODUCT_ALREADY_EXISTS: 'PRODUCT_ALREADY_EXISTS',
	PRODUCT_NOT_UPDATED: 'PRODUCT_NOT_UPDATED',
	PRODUCT_NOT_DELETED: 'PRODUCT_NOT_DELETED',
	PRODUCT_NOT_CREATED: 'PRODUCT_NOT_CREATED',
	PRODUCTS_NOT_FOUND: 'PRODUCTS_NOT_FOUND',
} as const

export const CartStatus = {
	CART_NOT_FOUND: 'CART_NOT_FOUND',
	CART_ALREADY_EXISTS: 'CART_ALREADY_EXISTS',
	PRODUCT_ALREADY_IN_CART: 'PRODUCT_ALREADY_IN_CART',
	PRODUCT_ADDED_TO_CART: 'PRODUCT_ADDED_TO_CART',
	PRODUCT_REMOVED_FROM_CART: 'PRODUCT_REMOVED_FROM_CART',
} as const

export const WishlistStatus = {
	WISHLIST_EMPTY: 'WISHLIST_EMPTY',
	PRODUCT_ALREADY_IN_WISHLIST: 'PRODUCT_ALREADY_IN_WISHLIST',
	PRODUCT_ADDED_TO_WISHLIST: 'PRODUCT_ADDED_TO_WISHLIST',
	PRODUCT_REMOVED_FROM_WISHLIST: 'PRODUCT_REMOVED_FROM_WISHLIST',
	WISHLIST_FOUND: 'WISHLIST_FOUND',
} as const

export const ReviewStatus = {
	REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
	REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
	REVIEW_FOUND: 'REVIEW_FOUND',
	REVIEW_ADDED: 'REVIEW_ADDED',
	REVIEW_NOT_ADDED: 'REVIEW_NOT_ADDED',
	REVIEW_DELETED: 'REVIEW_DELETED',
	ALREADY_REVIEWED: 'ALREADY_REVIEWED',
	REVIEW_EDITED: 'REVIEW_EDITED',
	REVIEW_NOT_EDITED: 'REVIEW_NOT_EDITED',
} as const
